// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjoMRcfRtjAhA8TeV_qI0dzbp9Pr0peUc',
    appId: '1:241096789678:web:c46661ec0c6b451bef673f',
    messagingSenderId: '241096789678',
    projectId: 'pneuma-messenger',
    authDomain: 'pneuma-messenger.firebaseapp.com',
    storageBucket: 'pneuma-messenger.firebasestorage.app',
    measurementId: 'G-1KJL91TTZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_PVVz-N-crxQq5mz5VQ2nKsYV9yOJky0',
    appId: '1:241096789678:android:dbd0ca7b7bbdc071ef673f',
    messagingSenderId: '241096789678',
    projectId: 'pneuma-messenger',
    storageBucket: 'pneuma-messenger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDFZabW1TilNPSTs_IQ3_EGG0WKr5tjDg',
    appId: '1:241096789678:ios:ef708ba91139857def673f',
    messagingSenderId: '241096789678',
    projectId: 'pneuma-messenger',
    storageBucket: 'pneuma-messenger.firebasestorage.app',
    iosBundleId: 'com.example.pneumaMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDFZabW1TilNPSTs_IQ3_EGG0WKr5tjDg',
    appId: '1:241096789678:ios:ef708ba91139857def673f',
    messagingSenderId: '241096789678',
    projectId: 'pneuma-messenger',
    storageBucket: 'pneuma-messenger.firebasestorage.app',
    iosBundleId: 'com.example.pneumaMessenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjoMRcfRtjAhA8TeV_qI0dzbp9Pr0peUc',
    appId: '1:241096789678:web:2f809c4cb7d9ed95ef673f',
    messagingSenderId: '241096789678',
    projectId: 'pneuma-messenger',
    authDomain: 'pneuma-messenger.firebaseapp.com',
    storageBucket: 'pneuma-messenger.firebasestorage.app',
    measurementId: 'G-0P75KV19XC',
  );

}